export const en = {
  fcr_home_page_scene_option_online_proctoring: '	Online Proctoring',
  fcr_home_page_parameter_label_ai: '	AI invigilation',
  fcr_home_page_parameter_label_ai_option_enable: 'Enable',
  fcr_home_page_parameter_label_ai_option_disable: 'Disable',
  fcr_role_proctor: 'Proctor',
  fcr_role_test_taker: 'Test Taker',
  fcr_room_button_exam_start: 'Start Exam',
  fcr_room_button_exam_end: 'End Exam',
  fcr_room_button_leave: 'Leave',
  fcr_room_button_broadcast: 'Broadcast',
  fcr_room_tab_all: 'ALL',
  fcr_room_tab_abnormal: 'Abnormal',
  fcr_room_tab_focus: 'Focus',
  fcr_room_label_room_number: '	Room Number',
  fcr_room_label_time_remaining: '	Time Remaining',
  fcr_room_label_start_time: '	Start Time',
  fcr_room_label_all_videos: '	All Videos',
  fcr_room_label_wait_you_start_exam: '	Waiting you start the exam',
  fcr_room_label_exam_over: '	The exam is over',
  fcr_room_label_wait_teacher_start_exam: '	Please wait until the proctor starts the exam',
  fcr_room_label_broadcasting: '	You‘re broadcasting',
  fcr_room_tips_join_failed: '	Failed to join exam, please try again',
  fcr_room_tips_exam_not_started: '	Exam has not started',
  fcr_sub_room_label_monitor: '	Real Time Monitor',
  fcr_sub_room_label_replay: 'Replay',
  fcr_sub_room_label_report_behavior: '	Report a suspicious behavior',
  fcr_sub_room_option_report_behavior_default: '	Select a reason',
  fcr_sub_room_button_report_behavior_submit: 'Submit',
  fcr_exam_prep_label_exam_prep: '	Exam Prep',
  fcr_exam_prep_label_device_test: 'Device Test',
  fcr_exam_prep_label_take_photo: '	Take your photo',
  fcr_exam_prep_label_share_screen: '	Share entire screen',
  fcr_exam_prep_label_test_exam_device: 'Please test exam device',
  fcr_exam_prep_label_camera: 'Camera',
  fcr_exam_prep_label_microphone: 'Microphone',
  fcr_exam_prep_label_speaker: 'Speaker',
  fcr_exam_prep_label_align_face: 'Please align your face within the frame below',
  fcr_exam_prep_label_authorize_share_screen: 'Please authorize the screen to share',
  fcr_exam_prep_label_join_exam: 'Now, you can join the exam!',
  fcr_exam_prep_button_test: 'Test',
  fcr_exam_prep_button_cancel: 'Cancel',
  fcr_exam_prep_button_next_step: '	Next step',
  fcr_exam_prep_button_take_photo: '	Take Photo',
  fcr_exam_prep_button_retake: 'Retake',
  fcr_exam_prep_button_previous: 'Previous',
  fcr_exam_prep_button_confirm_sharing: 'Confirm Sharing',
  fcr_exam_prep_button_join_exam: '	Join Exam',
  fcr_exam_prep_option_camera_disabled: 'Disabled',
  fcr_exam_prep_option_microphone_disabled: 'Disabled',
  fcr_device_test_label_hello: 'Hello',
  fcr_device_test_label_upcoming: 'Upcoming',
  fcr_device_test_label_on_going: '	On Going',
  fcr_device_test_label_not_started: 'Not Started',
  fcr_device_test_label_closed: 'Closed',
  fcr_device_test_label_switch_camera: 'Switch Camera',
  fcr_device_test_label_no_access_camera: '	No Access to Camera',
  fcr_device_test_label_allow_access_camera:
    'Allow online proctoring to access your camera in Setting-Privacy-Camera',
  fcr_device_test_label_leave_exam: 'Do you really want to leave the exam?',
  fcr_device_test_label_check_screen: 'Please align you in the screen',
  fcr_device_test_button_join_exam: 'Join Exam',
  fcr_device_test_button_stay: 'Stay',
  fcr_device_test_button_leave: 'Leave',
  fcr_device_test_label_enable: 'On',
  fcr_device_test_label_disable: 'Off',
  fcr_device_test_label_default: 'Default',
  fcr_exam_prep_label_close_screen_share: 'Don‘t turn off screen share during the exam',
  fcr_alert_title: 'Prompt',
  fcr_room_button_leave_confirm: 'Confirm',
  fcr_sub_room_option_report_ID_verification: 'ID Verification',
  fcr_sub_room_option_report_multiple_people: 'Multiple People',
  fcr_sub_room_option_report_electronic_devices: 'Electronic Devices',
  fcr_sub_room_option_report_paperworks: 'Paperworks',
  fcr_sub_room_label_AI_description: 'Description from AI',
  fcr_sub_room_label_Human_description: 'Description from human being',
  fcr_sub_room_label_web_disconnected: 'Web disconnected',
  edu_error: {
    '600000': 'Failed to join the classroom',
    '600001': 'Failed to join the classroom',
    '600002': 'Failed to validate extension, upload',
    '600003': 'Failed to upload: file format not supported',
    '600004': 'Failed to upload file to storage',
    '600005': 'Failed to upload file',
    '600006': 'Whiteboard not available',
    '600007': 'Whiteboard not available',
    '600008': 'Whiteboard not available',
    '600009': 'Failed to close whiteboard',
    '600010': 'Whiteboard not available',
    '600011': 'Whiteboard not available',
    '600012': 'Unsupported file format',
    '600013': 'Classroom not available',
    '600014': 'Failed to kick out',
    '600015': 'Local user information not obtained',
    '600016': 'Failed to get off the podium',
    '600017': 'Failed to reject hand up',
    '600018': 'Failed cancel hand up',
    '600019': 'Failed to start carousel ',
    '600020': 'Failed to stop carousel',
    '600021': 'Failed to mute',
    '600022': 'Failed to close widget',
    '600023': 'Failed to accept hand up',
    '600024': 'Failed to hand up',
    '600025': 'Failed to close widget',
    '600026': 'Data error',
    '600027': 'Failed to send reward',
    '600028': 'Failed to enable video',
    '600029': 'Failed to disable video',
    '600030': 'Failed to toggle video',
    '600031': 'Failed to enable audio',
    '600032': 'Failed to disable audio',
    '600033': 'Failed to toggle audio',
    '600034': 'Failed to load whiteboard',
    '600035': 'Failed to start recording',
    '600036': 'Failed to stop recording',
    '600037': 'Failed to join RTC',
    '600038': 'Failed to leave RTC',
    '600039': 'Failed to load whiteboard',
    '600040': 'Failed to leave whiteboard',
    '600041': 'Invalid to classroom state',
    '600042': 'Invalid to RTC state',
    '600043': 'Invalid to whiteboard state',
    '600044': 'Failed to leave the classroom',
    '600045': 'RTE uninitialized',
    '600046': 'Failed to hand up',
    '600047': 'Whitboard unavailable',
    '600048': 'Failed to get history chat message',
    '600049': 'Failed to get history chat message',
    '600050': 'Failed to get conversation list',
    '600051': 'Failed to send message',
    '600052': 'Failed to send message',
    '600053': 'Failed to mute users',
    '600054': 'Failed to unmute users',
    '600055': 'Device manager not initialized',
    '600056': 'Invalid students number',
    '600057': 'Failed to delete cloud resource',
    '600058': 'Failed to load cloud resources',
    '600059': 'Failed to update classroom state',
    '600060': 'Failed to start screen share',
    '600061': 'Failed to stop screen share',
    '600062': 'Failed to update local device state',
    '600063': 'Failed to update remote device state',
    '600064': 'Failed to upload file to cloud resource',
    '600065': 'Failed to update ExtApp properties',
    '600066': 'Failed to update ExtApp properties',
    '600067': 'Failed to convert cloud resource',
    '600068': 'The resource is converting',
    '600069': 'Failed to get all students off the podium',
    '600070': 'Failed to update Whiteboard state',
    '600071': 'Classroom state not initialized',
    '600072': 'Whiteboard connection timeout',
    '600073': 'Failed to report information',
    '600074': 'The resource is already opened',
    '600075': 'Failed to get on stage',
    '600077': 'Failed to get upload checkpoint',
    '600078': 'Failed to switch stream type',
    '600079': 'Failed to enable dual stream',
    '600080': 'Failed to set low stream parameter',
    '600090': 'Failed to join rdc room',
    '600096': 'Failed to set latency level',
  },
  edu_serv_error: {
    '20400200': 'UserUuid is required!',
    '20400300': 'Stream is required!',
    '20401000': 'User token invalid!',
    '20401001': 'Role cannot join room!',
    '20403001': 'This role is full in the room!',
    '20403002': 'Room is full!',
    '20404000': 'Process not exist!',
    '20404100': 'Room not exist!',
    '20410101': 'Sequence is obsolete!',
    '20404200': 'User not exist!',
    '20404300': 'Stream not exist!',
    '20404400': 'Room template not exist!',
    '20409000': 'Process conflict!',
    '20409100': 'Room conflict!',
    '20409300': 'Stream uuid conflict!',
    '20410100': 'Room is end!',
    '20410200': 'User not online!',
    '20500300': 'Create stream failed!',
    '20500001': 'Generate token failed!',
    '30403100': 'You cannot join room.',
    '30400420': 'Please set whiteboard token in Agora console.',
    '30403200': 'You cannot send chat message.',
    '30404200': 'The teacher is not in the room.',
    '30409100': 'Session is started.',
    '30409101': 'Session is ended.',
    '30409102': 'Screen has shared.',
    '30409103': 'Screen has not shared.',
    '30409104': 'roomType conflicts.',
    '30409410': 'Record is not started.',
    '30409411': 'Record is running.',
    '30400412': 'Param "url" or "rootUrl" is required in web mode.',
    '30500420': 'Whiteboard failed to create room.',
    '30409440': 'Reward reached room limit.',
    '30409430': 'Operate conflict.',
    '30404430': 'Private speech not found.',
    '30404460': 'process not found.',
    '30404461': 'progress not found.',
    '30409460': 'progress conflict.',
    '30404462': 'accept not found.',
    '30410460': 'process unable.',
    '30429460': 'progress reached max wait.',
    '30429461': 'accept reached max count.',
    '30409601': 'user is being invited',
  },
};
