export const en = {
  fcr_home_page_scene_option_online_proctoring: "	Online Proctoring",
  fcr_home_page_parameter_label_ai: "	AI invigilation",
  fcr_home_page_parameter_label_ai_option_enable: "Enable",
  fcr_home_page_parameter_label_ai_option_disable: "Disable",
  fcr_role_proctor: "Proctor",
  fcr_role_test_taker: "	Test Taker",
  fcr_room_button_exam_start: "	Start Exam",
  fcr_room_button_exam_end: "	End Exam",
  fcr_room_button_leave: "Leave",
  fcr_room_button_broadcast: "Broadcast",
  fcr_room_tab_all: "ALL",
  fcr_room_tab_abnormal: "Abnormal",
  fcr_room_tab_focus: "Focus",
  fcr_room_label_room_number: "	Room Number",
  fcr_room_label_time_remaining: "	Time Remaining",
  fcr_room_label_start_time: "	Start Time",
  fcr_room_label_all_videos: "	All Videos",
  fcr_room_label_wait_you_start_exam: "	Waiting you start the exam",
  fcr_room_label_exam_over: "	The exam is over",
  fcr_room_label_wait_teacher_start_exam:
    "	Please wait until the proctor starts the exam",
  fcr_room_label_broadcasting: "	You‘re broadcasting",
  fcr_room_tips_join_failed: "	Failed to join exam, please try again",
  fcr_room_tips_exam_not_started: "	Exam has not started",
  fcr_sub_room_label_monitor: "	Real Time Monitor",
  fcr_sub_room_label_replay: "Replay",
  fcr_sub_room_label_report_behavior: "	Report a suspicious behavior",
  fcr_sub_room_option_report_behavior_default: "	Select a reason",
  fcr_sub_room_button_report_behavior_submit: "Submit",
  fcr_exam_prep_label_exam_prep: "	Exam Prep",
  fcr_exam_prep_label_device_test: "Device Test",
  fcr_exam_prep_label_take_photo: "	Take your photo",
  fcr_exam_prep_label_share_screen: "	Share entire screen",
  fcr_exam_prep_label_test_exam_device: "Please test exam device",
  fcr_exam_prep_label_camera: "Camera",
  fcr_exam_prep_label_microphone: "Microphone",
  fcr_exam_prep_label_speaker: "Speaker",
  fcr_exam_prep_label_align_:
    "face	Please align your face within the frame below",
  fcr_exam_prep_label_authorize_share_:
    "screen	Please authorize the screen to share",
  fcr_exam_prep_label_join_: " exam	Now, you can join the exam!",
  fcr_exam_prep_button_test: "Test",
  fcr_exam_prep_button_cancel: "Cancel",
  fcr_exam_prep_button_next_step: "	Next step",
  fcr_exam_prep_button_take_photo: "	Take Photo",
  fcr_exam_prep_button_retake: "Retake",
  fcr_exam_prep_button_previous: "Previous",
  fcr_exam_prep_button_confirm_sharing: "Confirm Sharing",
  fcr_exam_prep_button_join_exam: "	Join Exam",
  fcr_exam_prep_option_camera_disabled: "Disabled",
  fcr_exam_prep_option_microphone_disabled: "Disabled",
  fcr_device_test_label_hello: "Hello",
  fcr_device_test_label_upcoming: "Upcoming",
  fcr_device_test_label_on_going: "	On Going",
  fcr_device_test_label_not_started: "Not Started",
  fcr_device_test_label_closed: "Closed",
  fcr_device_test_label_switch_camera: "Switch Camera",
  fcr_device_test_label_no_access_camera: "	No Access to Camera",
  fcr_device_test_label_allow_access_camera:
    "Allow online proctoring to access your camera in Setting-Privacy-Camera",
  fcr_device_test_label_leave_exam: "Do you really want to leave the exam?",
  fcr_device_test_label_check_screen: "Please align you in the screen",
  fcr_device_test_button_join_exam: "Join Exam",
  fcr_device_test_button_stay: "Stay",
  fcr_device_test_button_leave: "Leave",
};
