export const zh = {
  fcr_home_page_scene_option_online_proctoring: "在线监考",
  fcr_home_page_parameter_label_ai: "AI监考",
  fcr_home_page_parameter_label_ai_option_enable: "开启",
  fcr_home_page_parameter_label_ai_option_disable: "关闭",
  fcr_role_proctor: "考官",
  fcr_role_test_taker: "考生",
  fcr_room_button_exam_start: "开始考试",
  fcr_room_button_exam_end: "结束考试",
  fcr_room_button_leave: "离开考场",
  fcr_room_button_broadcast: "广播",
  fcr_room_tab_all: "全部",
  fcr_room_tab_abnormal: "异常",
  fcr_room_tab_focus: "关注",
  fcr_room_label_room_number: "房间号",
  fcr_room_label_time_remaining: "倒计时",
  fcr_room_label_start_time: "开始时间",
  fcr_room_label_all_videos: "全部窗口",
  fcr_room_label_wait_you_start_exam: "等待你开始考试",
  fcr_room_label_exam_over: "考试已结束",
  fcr_room_label_wait_teacher_start_exam: "请等待老师开始考试",
  fcr_room_label_broadcasting: "你正在广播",
  fcr_room_tips_join_failed: "加入考试失败，请重试",
  fcr_room_tips_exam_not_started: "考试未开始",
  fcr_sub_room_label_monitor: "实时监控",
  fcr_sub_room_label_replay: "录像回放",
  fcr_sub_room_label_report_behavior: "报告可疑行为",
  fcr_sub_room_option_report_behavior_default: "选择上报原因",
  fcr_sub_room_button_report_behavior_submit: "提交",
  fcr_exam_prep_label_exam_prep: "考试准备",
  fcr_exam_prep_label_device_test: "设备检测",
  fcr_exam_prep_label_take_photo: "拍摄照片",
  fcr_exam_prep_label_share_screen: "共享屏幕",
  fcr_exam_prep_label_test_exam_device: "请检查考试设备",
  fcr_exam_prep_label_camera: "摄像头",
  fcr_exam_prep_label_microphone: "麦克风",
  fcr_exam_prep_label_speaker: "扬声器",
  fcr_exam_prep_label_align_: "face	请将你的脸对准下面区域",
  fcr_exam_prep_label_authorize_share_: "screen	请授权要分享的屏幕",
  fcr_exam_prep_label_join_: "exam	现在可以加入考试啦！",
  fcr_exam_prep_button_test: "测试",
  fcr_exam_prep_button_cancel: "取消",
  fcr_exam_prep_button_next_step: "下一步",
  fcr_exam_prep_button_take_photo: "拍照",
  fcr_exam_prep_button_retake: "重新拍照",
  fcr_exam_prep_button_previous: "上一步",
  fcr_exam_prep_button_confirm_sharing: "确认共享",
  fcr_exam_prep_button_join_exam: "加入考试",
  fcr_exam_prep_option_camera_disabled: "禁用",
  fcr_exam_prep_option_microphone_disabled: "禁用",
  fcr_device_test_label_hello: "你好",
  fcr_device_test_label_upcoming: "即将开始",
  fcr_device_test_label_on_going: "已经开始",
  fcr_device_test_label_not_started: "未开始",
  fcr_device_test_label_closed: "已结束",
  fcr_device_test_label_switch_camera: "切换摄像头",
  fcr_device_test_label_no_access_camera: "获取不到摄像头",
  fcr_device_test_label_allow_access_camera:
    "在设置-隐私-相机中允许在线监考访问您的摄像头",
  fcr_device_test_label_leave_exam: "真的要退出考试吗？",
  fcr_device_test_label_check_screen: "请将你置于画面中",
  fcr_device_test_button_join_exam: "正式进入考场",
  fcr_device_test_button_stay: "留下",
  fcr_device_test_button_leave: "退出",
};
